<?xml version="1.0" encoding="utf-8"?><Database Name="WEBJOB" Class="JobContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ADMIN\SQLEXPRESS;Initial Catalog=WEBJOB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WEBJOBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="id_account" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[confirm]" Member="confirm" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="account_employee" Member="employees" ThisKey="id_account" OtherKey="id_account" Type="employee" />
      <Association Name="account_employer" Member="employers" ThisKey="id_account" OtherKey="id_account" Type="employer" />
      <Association Name="role_account" Member="role" ThisKey="id_role" OtherKey="id_role" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comment_employee" Member="comment_employees">
    <Type Name="comment_employee">
      <Column Name="id_comments" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_employee" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_job_detail" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="comment_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="comment_employee_comment_employer" Member="comment_employers" ThisKey="id_comments" OtherKey="Id_comment_employee" Type="comment_employer" />
      <Association Name="employee_comment_employee" Member="employee" ThisKey="id_employee" OtherKey="id_employee" Type="employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comment_employer" Member="comment_employers">
    <Type Name="comment_employer">
      <Column Name="id_comment" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="comment_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_comment_employee" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_employer" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="comment_employee_comment_employer" Member="comment_employee" ThisKey="Id_comment_employee" OtherKey="id_comments" Type="comment_employee" IsForeignKey="true" />
      <Association Name="employer_comment_employer" Member="employer" ThisKey="id_employer" OtherKey="id_employer" Type="employer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.company" Member="companies">
    <Type Name="company">
      <Column Name="id_company" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_company" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="phonenumber" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="company_following_company" Member="following_companies" ThisKey="id_company" OtherKey="id_company" Type="following_company" />
      <Association Name="company_job" Member="jobs" ThisKey="id_company" OtherKey="id_company" Type="job" />
    </Type>
  </Table>
  <Table Name="dbo.cover_letter" Member="cover_letters">
    <Type Name="cover_letter">
      <Column Name="id_letter" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="cover_letter_employee" Member="employees" ThisKey="id_letter" OtherKey="id_letter" Type="employee" />
    </Type>
  </Table>
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="id_employee" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_employee" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="day_birth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="phonenumber_employee" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address_employee" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="active_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_letter" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_profile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="employee_comment_employee" Member="comment_employees" ThisKey="id_employee" OtherKey="id_employee" Type="comment_employee" />
      <Association Name="employee_following_company" Member="following_companies" ThisKey="id_employee" OtherKey="id_employee" Type="following_company" />
      <Association Name="employee_following_job" Member="following_jobs" ThisKey="id_employee" OtherKey="id_employee" Type="following_job" />
      <Association Name="account_employee" Member="account" ThisKey="id_account" OtherKey="id_account" Type="account" IsForeignKey="true" />
      <Association Name="cover_letter_employee" Member="cover_letter" ThisKey="id_letter" OtherKey="id_letter" Type="cover_letter" IsForeignKey="true" />
      <Association Name="profile_employee" Member="profile" ThisKey="id_profile" OtherKey="id_profile" Type="profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employer" Member="employers">
    <Type Name="employer">
      <Column Name="id_employer" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_employer" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="day_birth_employer" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="phonenumer_employer" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="active_status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="id_account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="employer_comment_employer" Member="comment_employers" ThisKey="id_employer" OtherKey="id_employer" Type="comment_employer" />
      <Association Name="account_employer" Member="account" ThisKey="id_account" OtherKey="id_account" Type="account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.following_company" Member="following_companies">
    <Type Name="following_company">
      <Column Name="id_employee" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_company" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="company_following_company" Member="company" ThisKey="id_company" OtherKey="id_company" Type="company" IsForeignKey="true" />
      <Association Name="employee_following_company" Member="employee" ThisKey="id_employee" OtherKey="id_employee" Type="employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.following_job" Member="following_jobs">
    <Type Name="following_job">
      <Column Name="id_employee" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_job_detail" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="employee_following_job" Member="employee" ThisKey="id_employee" OtherKey="id_employee" Type="employee" IsForeignKey="true" />
      <Association Name="job_detail_following_job" Member="job_detail" ThisKey="id_job_detail" OtherKey="id_job_detail" Type="job_detail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.job" Member="jobs">
    <Type Name="job">
      <Column Name="id_job" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="release_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="id_company" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id_title" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="job_job_detail" Member="job_details" ThisKey="id_job" OtherKey="id_job" Type="job_detail" />
      <Association Name="company_job" Member="company" ThisKey="id_company" OtherKey="id_company" Type="company" IsForeignKey="true" />
      <Association Name="job_title_job" Member="job_title" ThisKey="id_job" OtherKey="id_title" Type="job_title" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.job_detail" Member="job_details">
    <Type Name="job_detail">
      <Column Name="id_job_detail" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="salary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_job" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id_skill" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="job_detail_following_job" Member="following_jobs" ThisKey="id_job_detail" OtherKey="id_job_detail" Type="following_job" />
      <Association Name="job_job_detail" Member="job" ThisKey="id_job" OtherKey="id_job" Type="job" IsForeignKey="true" />
      <Association Name="job_skill_job_detail" Member="job_skill" ThisKey="id_skill" OtherKey="id_skill" Type="job_skill" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.job_skill" Member="job_skills">
    <Type Name="job_skill">
      <Column Name="id_skill" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_skill" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="job_skill_job_detail" Member="job_details" ThisKey="id_skill" OtherKey="id_skill" Type="job_detail" />
    </Type>
  </Table>
  <Table Name="dbo.job_title" Member="job_titles">
    <Type Name="job_title">
      <Column Name="id_title" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="job_title_job" Member="job" ThisKey="id_title" OtherKey="id_job" Type="job" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.profile" Member="profiles">
    <Type Name="profile">
      <Column Name="id_profile" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cv" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="profile_employee" Member="employees" ThisKey="id_profile" OtherKey="id_profile" Type="employee" />
    </Type>
  </Table>
  <Table Name="dbo.rating" Member="ratings">
    <Type Name="rating">
      <Column Name="id_rate" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_employee" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="rate_star" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_company" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.role" Member="roles">
    <Type Name="role">
      <Column Name="id_role" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_role" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="role_account" Member="accounts" ThisKey="id_role" OtherKey="id_role" Type="account" />
    </Type>
  </Table>
</Database>